### ISSUE TITLE
maverick-api import error

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#1003]
```
Aug 09 18:48:14 maverick-desktopvm api.sh[97357]: Traceback (most recent call last):
Aug 09 18:48:14 maverick-desktopvm api.sh[97357]:   File "/srv/maverick/software/maverick-api/maverick-api.py", line 16, in <module>
Aug 09 18:48:14 maverick-desktopvm api.sh[97357]:     from maverick_api.modules.base.setup.config import MavConfig
Aug 09 18:48:14 maverick-desktopvm api.sh[97357]:   File "/srv/maverick/software/maverick-api/maverick_api/modules/__init__.py", line 9, in <module>
Aug 09 18:48:14 maverick-desktopvm api.sh[97357]:     from graphql.pyutils.event_emitter import EventEmitter
Aug 09 18:48:14 maverick-desktopvm api.sh[97357]: ModuleNotFoundError: No module named 'graphql.pyutils.event_emitter'
Aug 09 18:48:14 maverick-desktopvm systemd[1]: maverick-api@system.service: Main process exited, code=exited, status=1/FAILURE
```

graphql_core seem to have changed/deprecated graphql.pyutils.event_emitter

**Comment by fnoop** [comment]
Looks like EventEmitter has been replaced with SimplePubSub

https://github.com/graphql-python/graphql-core/commit/2f25886950c9cbbea9663a921dc63945f0fc43c7#diff-5507dfe2ed2aef45270a83f30e9ccdc8d58b5802742e3d8e97c0aa85b7e7ba3b

**Comment by fnoop** [comment]
EventEmitterAsyncIterator has been replaced with SimplePubSubIterator

**Comment by fnoop** [comment]
path.name error:
```
Sep 12 18:15:58 maverick-desktopvm api.sh[147326]:   File "/srv/maverick/software/maverick-api/maverick_api/modules/__init__.py", line 115, in generate_schema
Sep 12 18:15:58 maverick-desktopvm api.sh[147326]:     module_folder_name = module_folder_finder.path.name
Sep 12 18:15:58 maverick-desktopvm api.sh[147326]: AttributeError: 'str' object has no attribute 'name'
```
