### ISSUE TITLE
Ros/mavros fails to start on raspberry pi zero

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#749]
Works on raspberry pi 3 but not pi zero.  If you start rosmaster and mavros manually after boot they work fine, so some kind of timing issue.

**Comment by fnoop** [comment]
Looks like a watchdog doesn't see startup complete or responding within a minute so kills it:
```
Mar 28 07:45:36 maverick-raspberrylite systemd[1]: Started Maverick ROS Master - fc.
Mar 28 07:46:36 maverick-raspberrylite rosmaster.sh[585]: ERROR: could not contact master [http://maverick-raspberrylite:11311/]
Mar 28 07:46:36 maverick-raspberrylite rosmaster.sh[585]: The traceback for the exception was written to the log file
Mar 28 07:46:36 maverick-raspberrylite rosmaster.sh[585]: ... logging to /srv/maverick/var/log/ros/fc/a8ec0398-3253-11e8-ad85-b827ebfc4258/roslaunch-maverick-raspberrylite-657.log
```
Try depending the systemd service and let it start later in the boot sequence.

**Comment by fnoop** [comment]
Resetting boot order isn't helping, the process is starting but then dies:
```
[roslaunch][INFO] 2018-03-28 10:05:37,533: master.is_running[http://maverick-raspberrylite:11311/]
[roslaunch][INFO] 2018-03-28 10:05:37,640: master.is_running[http://maverick-raspberrylite:11311/]
[roslaunch][INFO] 2018-03-28 10:05:37,696: master.is_running[http://maverick-raspberrylite:11311/]
[roslaunch][ERROR] 2018-03-28 10:05:37,702: ERROR: could not contact master [http://maverick-raspberrylite:11311/]
[roslaunch][ERROR] 2018-03-28 10:05:37,788: The traceback for the exception was written to the log file
[roslaunch][ERROR] 2018-03-28 10:05:37,856: Traceback (most recent call last):
  File "/srv/maverick/software/ros/current/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/srv/maverick/software/ros/current/lib/python2.7/dist-packages/roslaunch/parent.py", line 279, in start
    self.runner.launch()
  File "/srv/maverick/software/ros/current/lib/python2.7/dist-packages/roslaunch/launch.py", line 657, in launch
    self._setup()
  File "/srv/maverick/software/ros/current/lib/python2.7/dist-packages/roslaunch/launch.py", line 632, in _setup
    launched = self._launch_master()
  File "/srv/maverick/software/ros/current/lib/python2.7/dist-packages/roslaunch/launch.py", line 410, in _launch_master
    raise RLException("ERROR: could not contact master [%s]"%m.uri)
RLException: ERROR: could not contact master [http://maverick-raspberrylite:11311/]

```

**Comment by fnoop** [comment]
Try adding restart to the service manifest.  This only occurs on very slow platforms - pi zero, has not been seen on other platforms.

**Comment by fnoop** [comment]
Turned off visiond in raspberrylite profile which was hammering cpu on startup with no camera and hurting performance, leading to rosmaster to fail.  rosmaster now starts on boot, albeit after a couple of failed restarts.

**Comment by fnoop** [comment]
still not booting reliably on pi zero

**Comment by fnoop** [comment]
Instead of configurable delay, add a mechanism to mavros startup that waits for rosmaster port to be ready.  Much more reliable.
