### ISSUE TITLE
Network: netinfo not showing mode

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#772]
maverick-netinfo should show whether an interface is in managed or monitor mode

**Comment by fnoop** [comment]
Large amount of info retrieved from netinfo fact when running directly, but when run through maverick-netinfo is not present.  Weird.

**Comment by fnoop** [comment]
pyric fails on getcard call when called under module:
```
Traceback (most recent call last):
  File "/srv/maverick/software/maverick/bin/maverick-netinfo", line 47, in <module>
    _netinfo.getinfo()
  File "/srv/maverick/software/maverick/manifests/maverick-modules/maverick_network/facts.d/netinfo.py", line 102, in getinfo
    _ifobj = pyw.getcard(self._if)
  File "/usr/local/lib/python2.7/dist-packages/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/pyric/pyw.py", line 1028, in devinfo
    idx = _ifindex_(dev)
  File "/usr/local/lib/python2.7/dist-packages/pyric/pyw.py", line 2165, in _ifindex_
    if iosock is None: return _iostub_(_ifindex_, dev)
  File "/usr/local/lib/python2.7/dist-packages/pyric/pyw.py", line 2217, in _iostub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/pyric/pyw.py", line 2172, in _ifindex_
    raise pyric.error(pyric.EINVAL, e)
pyric.error: [Errno 22] ifr_ifrn (dev name) wman0 is invalid
```

**Comment by fnoop** [comment]
Ah, maverick-netinfo not passing the interface name into the module as a string.  Casting fixes.
