### ISSUE TITLE
raspberry build issues

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#840]
*FIXED*
```
Error: Systemd start for maverick-motd failed!
journalctl log for maverick-motd:
-- Logs begin at Sat 2019-05-11 07:17:02 BST, end at Sat 2019-05-11 08:06:57 BST. --
May 11 08:06:54 maverick-raspberry systemd[1]: Starting Maverick MOTD Creator...
May 11 08:06:57 maverick-raspberry sh[1886]: Traceback (most recent call last):
May 11 08:06:57 maverick-raspberry sh[1886]:   File "/srv/maverick/software/maverick/bin/maverick-info", line 68, in <module>
May 11 08:06:57 maverick-raspberry sh[1886]:     print(twocols('C/G Mem Split', '\t\t' +str(raspberry.data['memcpu'])+' / '+str(raspberry.data['memgpu'])))
May 11 08:06:57 maverick-raspberry sh[1886]: KeyError: 'memcpu'
May 11 08:06:57 maverick-raspberry systemd[1]: maverick-motd.service: Main process exited, code=exited, status=1/FAILURE
May 11 08:06:57 maverick-raspberry systemd[1]: Failed to start Maverick MOTD Creator.
May 11 08:06:57 maverick-raspberry systemd[1]: maverick-motd.service: Unit entered failed state.
May 11 08:06:57 maverick-raspberry systemd[1]: maverick-motd.service: Failed with result 'exit-code'.

Error: /Stage[main]/Base::Console/Service_wrapper[maverick-motd]/Service[maverick-motd]/ensure: change from 'stopped' to 'running' failed: Systemd start for maverick-motd failed!
journalctl log for maverick-motd:
-- Logs begin at Sat 2019-05-11 07:17:02 BST, end at Sat 2019-05-11 08:06:57 BST. --
May 11 08:06:54 maverick-raspberry systemd[1]: Starting Maverick MOTD Creator...
May 11 08:06:57 maverick-raspberry sh[1886]: Traceback (most recent call last):
May 11 08:06:57 maverick-raspberry sh[1886]:   File "/srv/maverick/software/maverick/bin/maverick-info", line 68, in <module>
May 11 08:06:57 maverick-raspberry sh[1886]:     print(twocols('C/G Mem Split', '\t\t' +str(raspberry.data['memcpu'])+' / '+str(raspberry.data['memgpu'])))
May 11 08:06:57 maverick-raspberry sh[1886]: KeyError: 'memcpu'
May 11 08:06:57 maverick-raspberry systemd[1]: maverick-motd.service: Main process exited, code=exited, status=1/FAILURE
May 11 08:06:57 maverick-raspberry systemd[1]: Failed to start Maverick MOTD Creator.
May 11 08:06:57 maverick-raspberry systemd[1]: maverick-motd.service: Unit entered failed state.
May 11 08:06:57 maverick-raspberry systemd[1]: maverick-motd.service: Failed with result 'exit-code'.
```

**Comment by fnoop** [comment]
```
Error: Execution of '/usr/bin/apt-key adv --no-tty --keyserver pgp.mit.edu --recv-keys 74A5E9C458E1A431F1DA57A71657198823E52A61' returned 2: Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.2Z907qZtOY/gpg.1.sh --no-tty --keyserver pgp.mit.edu --recv-keys 74A5E9C458E1A431F1DA57A71657198823E52A61
gpg: keyserver receive failed: No data
Error: /Stage[main]/Maverick_network::Zerotier/Apt::Key[zerotier]/Apt_key[zerotier]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/bin/apt-key adv --no-tty --keyserver pgp.mit.edu --recv-keys 74A5E9C458E1A431F1DA57A71657198823E52A61' returned 2: Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.2Z907qZtOY/gpg.1.sh --no-tty --keyserver pgp.mit.edu --recv-keys 74A5E9C458E1A431F1DA57A71657198823E52A61
gpg: keyserver receive failed: No data
```

**Comment by fnoop** [comment]
```
[bootstrap] [mav@maverick-raspberry ~]$ maverick info

Maverick - UAV Companion Computer System - Version 2.0.0-dev

WARNING: Maverick is using branch:master, not stable

Maverick Environment:    bootstrap

Vendor:			Raspberry Pi
Model:			3 Model B+
Physical RAM:		1024
Traceback (most recent call last):
  File "/srv/maverick/software/maverick/bin/maverick-info", line 68, in <module>
    print(twocols('C/G Mem Split', '\t\t' +str(raspberry.data['memcpu'])+' / '+str(raspberry.data['memgpu'])))
KeyError: 'memcpu'
```

**Comment by fnoop** [comment]
```
Error: Could not find command '/usr/bin/yarn'
Error: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-preinstall]/returns: change from 'notrun' to ['0'] failed: Could not find command '/usr/bin/yarn'
Notice: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-build]: Dependency Exec[codeserver-preinstall] has failures: true
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-build]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-symlink]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/File[/srv/maverick/var/build/.install_flag_codeserver]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-ext-python]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-ext-cplusplus]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-ext-vscodeicons]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-ext-onedarkpro]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-ext-nightowl]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-ext-gitlens]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-ext-vetur]: Skipping because of failed dependencies
Warning: /Stage[main]/Maverick_web::Codeserver/Exec[codeserver-ext-puppet]: Skipping because of failed dependencies
```

**Comment by fnoop** [comment]
```
Error: Could not find command '/usr/bin/gitbook'
Error: /Stage[main]/Maverick_web::Maverick_docs/Exec[gitbook-px4-install]/returns: change from 'notrun' to ['0'] failed: Could not find command '/usr/bin/gitbook'
Notice: /Stage[main]/Maverick_web::Maverick_docs/Exec[gitbook-px4-build]: Dependency Exec[gitbook-px4-install] has failures: true
Warning: /Stage[main]/Maverick_web::Maverick_docs/Exec[gitbook-px4-build]: Skipping because of failed dependencies
Error: Could not find command '/usr/bin/yarn'
Error: /Stage[main]/Maverick_web::Maverick_web/Exec[yarn-maverick-web]/returns: change from 'notrun' to ['0'] failed: Could not find command '/usr/bin/yarn'
Notice: /Stage[main]/Maverick_web::Maverick_web/File[/etc/systemd/system/maverick-webdev.service]: Dependency Exec[yarn-maverick-web] has failures: true
Warning: /Stage[main]/Maverick_web::Maverick_web/File[/etc/systemd/system/maverick-webdev.service]: Skipping because of failed dependencies
```

**Comment by fnoop** [comment]
`gst-rtsp-server` builds before it should and installs into /usr/lib

**Comment by fnoop** [comment]
npm packages not in path, because we're using nodejs npm:
```
[dev] [mav@maverick-raspberry ~/software/maverick]$ ls -l /opt/nodejs/bin/yarn
lrwxrwxrwx 1 root root 36 May 13 07:04 /opt/nodejs/bin/yarn -> ../lib/node_modules/yarn/bin/yarn.js
[dev] [mav@maverick-raspberry ~/software/maverick]$ yarn
-bash: yarn: command not found
```

**Comment by fnoop** [comment]
Stick with binary gstreamer for now, all other build issues resolved.
