### ISSUE TITLE
vision_landing not starting

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick#995]
```
mav[flight] [mav@maverick-nano ~]$ maverick log vision_landing

Maverick - UAV Companion Computer System - Version 1.2.0-beta4

WARNING: Maverick is using branch:master, not stable

Displaying service log: vision_landing
-- Logs begin at Tue 2020-09-22 09:46:41 BST. --
Sep 24 10:50:53 maverick-nano systemd[1]: Started Maverick - Vision Landing System.
Sep 24 10:50:53 maverick-nano vision_landing[22177]: Traceback (most recent call last):
Sep 24 10:50:53 maverick-nano vision_landing[22177]:   File "/srv/maverick/software/vision_landing/vision_landing", line 14, in <module>
Sep 24 10:50:53 maverick-nano vision_landing[22177]:     from dronekit import connect, VehicleMode, LocationGlobal, LocationGlobalRelative
Sep 24 10:50:53 maverick-nano vision_landing[22177]: ImportError: No module named dronekit
Sep 24 10:50:53 maverick-nano systemd[1]: maverick-vision_landing.service: Main process exited, code=exited, status=1/FAILURE
Sep 24 10:50:53 maverick-nano systemd[1]: maverick-vision_landing.service: Failed with result 'exit-code'.
```

**Comment by fnoop** [comment]
```
[flight] [mav@maverick-nano ~]$ /srv/maverick/software/vision_landing/vision_landing -c /srv/maverick/config/vision/vision_landing.conf
Traceback (most recent call last):
  File "/srv/maverick/software/vision_landing/vision_landing", line 14, in <module>
    from dronekit import connect, VehicleMode, LocationGlobal, LocationGlobalRelative
ImportError: No module named dronekit
```

**Comment by fnoop** [comment]
```
[flight] [mav@maverick-nano ~]$ pip list |grep dronekit
dronekit                      2.9.2
```
weird..

**Comment by fnoop** [comment]
```
[flight] [mav@maverick-nano ~]$ python
Python 3.7.8 (tags/v3.7.8:4b47a5b, Jul 21 2020, 19:30:15)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dronekit
```
it works..

**Comment by fnoop** [comment]
ack balls, vision_landing is still python2:
https://github.com/goodrobots/vision_landing/issues/114

add a pip install for dronekit in vision_landing manifest specifically for python2
